# Generated by Django 5.2.1 on 2025-05-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('postup', models.TextField()),
                ('kategorie', models.CharField(choices=[('hlavni', 'Hlavní jídlo'), ('dezert', 'Dezert'), ('polevka', 'Polévka'), ('predkrm', 'Předkrm'), ('napoj', 'Nápoj')], max_length=20)),
                ('obtiznost', models.CharField(choices=[('lehka', 'Lehká'), ('stredni', 'Střední'), ('tezka', 'Těžká')], max_length=20)),
                ('hodnoceni', models.FloatField(help_text='Hodnocení od 0 do 5')),
                ('doba_pripravy', models.PositiveIntegerField(help_text='Doba v minutách')),
                ('obrazek', models.ImageField(upload_to='recepty/')),
            ],
        ),
        migrations.CreateModel(
            name='Surovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('mnozstvi', models.CharField(blank=True, max_length=50)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suroviny', to='recepty.recept')),
            ],
        ),
    ]
