# Generated by Django 5.2.1 on 2025-05-30 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='recepty/'),
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hodnoceni', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Hodnocení od 1 do 5')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to='recepty.recept')),
                ('uzivatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
