# Generated by Django 5.2.1 on 2025-06-04 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0002_alter_recept_obrazek_recenze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenze',
            name='hodnoceni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recenze',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
