# Generated by Django 5.2.1 on 2025-06-04 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0003_alter_recenze_hodnoceni_alter_recenze_uzivatel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recept',
            name='upraveno',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
