# Generated by Django 5.2.1 on 2025-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0004_recept_autor_recept_upraveno_recept_vytvoreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='hodnoceni',
            field=models.FloatField(default=0, help_text='Hodnocení od 0 do 5'),
        ),
    ]
