# Generated by Django 5.2.1 on 2025-06-06 05:22

from django.conf import settings
from django.db import migrations, models

def remove_duplicate_reviews(apps, schema_editor):
    Recenze = apps.get_model('recepty', 'Recenze')
    db_alias = schema_editor.connection.alias
    
    # Získáme všechny recenze
    recenze = Recenze.objects.using(db_alias).all()
    seen = set()
    duplicates = []
    
    # Najdeme duplicity
    for r in recenze:
        key = (r.recept_id, r.uzivatel_id)
        if key in seen:
            duplicates.append(r.id)
        else:
            seen.add(key)
    
    # Smažeme duplicitní recenze
    if duplicates:
        Recenze.objects.using(db_alias).filter(id__in=duplicates).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0005_alter_recept_hodnoceni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_reviews),
        
        migrations.AlterModelOptions(
            name='recenze',
            options={'ordering': ['-datum'], 'verbose_name': 'Recenze', 'verbose_name_plural': 'Recenze'},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'ordering': ['-vytvoreno'], 'verbose_name': 'Recept', 'verbose_name_plural': 'Recepty'},
        ),
        migrations.AlterModelOptions(
            name='surovina',
            options={'ordering': ['id'], 'verbose_name': 'Surovina', 'verbose_name_plural': 'Suroviny'},
        ),
        migrations.AddIndex(
            model_name='recenze',
            index=models.Index(fields=['hodnoceni'], name='recepty_rec_hodnoce_2a6c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='recenze',
            index=models.Index(fields=['datum'], name='recepty_rec_datum_92bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='recept',
            index=models.Index(fields=['nazev'], name='recepty_rec_nazev_39454a_idx'),
        ),
        migrations.AddIndex(
            model_name='recept',
            index=models.Index(fields=['kategorie'], name='recepty_rec_kategor_d4f623_idx'),
        ),
        migrations.AddIndex(
            model_name='recept',
            index=models.Index(fields=['hodnoceni'], name='recepty_rec_hodnoce_2e4192_idx'),
        ),
        migrations.AddIndex(
            model_name='recept',
            index=models.Index(fields=['vytvoreno'], name='recepty_rec_vytvore_2fe02e_idx'),
        ),
        migrations.AddIndex(
            model_name='surovina',
            index=models.Index(fields=['nazev'], name='recepty_sur_nazev_caff6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recenze',
            unique_together={('recept', 'uzivatel')},
        ),
    ]
